# Generated by Django 4.1.5 on 2023-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pic1",
            field=models.ImageField(upload_to="product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic2",
            field=models.ImageField(upload_to="product"),
        ),
    ]
