# Generated by Django 4.1.5 on 2023-02-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_checkout_checkoutproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproducts",
            name="pid",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="paymentStatus",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done")], default=0),
        ),
    ]
