# Generated by Django 4.1.5 on 2023-02-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_checkoutproducts_pid_alter_checkout_paymentstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutproducts", old_name="Checkout", new_name="checkout",
        ),
    ]
