# Generated by Django 4.1.5 on 2023-02-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout", old_name="oderStatus", new_name="orderStatus",
        ),
    ]
