# Generated by Django 4.1.5 on 2023-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_rename_oderstatus_checkout_orderstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="totalAmount",
            field=models.IntegerField(default=None),
        ),
    ]
