# Generated by Django 4.1.5 on 2023-03-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0008_checkout_totalamount"),
    ]

    operations = [
        migrations.RemoveField(model_name="checkout", name="totalAmount",),
    ]
