# Generated by Django 4.1.5 on 2023-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0012_remove_checkout_totalamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer", name="otp", field=models.IntegerField(default=885965),
        ),
    ]
